### ISSUE TITLE
ability to enter a passage identifier to jump to it

### ISSUE THREAD

**Issue by jtauber** [scaife-viewer/readhomer#8]
Note that this might need to be in the reader widget itself so it can be used in cases where there is more than one reader widget

Reference Model: A2

**Comment by jtauber** [comment]
I think this is basically a text input field that replaces the row of 24 book links

**Comment by jtauber** [comment]
While the existing Homer Reference Input is useful with the Reader, I think the Homer Reader needs to replace the book row with it too (as mentioned in the previous comment).

Also probably needs a placeholder with an example of the format to use and we'll have to consider how to handle both books in #22 

Finally, I think it should submit on hitting return. I shouldn't have to click on lookup (although have the button there is fine as otherwise it might not be clear what to do; but my natural instinct is to hit enter and it doesn't work)

**Comment by paltman** [comment]
@jtauber so to be clear the action items are:

- [ ] do something with the **Homer Reader** widget (not sure exactly what)
- [ ] Add a placeholder to the input box
- [ ] Submit on Enter press

**Comment by jtauber** [comment]
"(not sure exactly what)" -> "text input field that replaces the row of 24 book links"

Instead of the row of 24 book links (which can only be used to retrieve a book at a time) put the text input / button from the separate widget there.

**Comment by jtauber** [comment]
Okay, after discussion, what I propose is:

The text input field replaces the row of 24 book links but there is also a toggle to get the passage reference from the store. If this is toggled, the text input will be disabled (but will still show the passage).

In short, this means each reader component can show its own passage OR get the passage from the store (where it is set by the Homer Reference Input).

With this change, there is no reason for both the Reader and Homer Reader. The 2x2 is still useful (and will be more useful with this change and will fulfill #5). The Parallel reader isn't that interesting until we actually get to #17.

**Comment by jtauber** [comment]
but see #26
